config/routes.rb
Wp102dv401::Application.routes.draw do

  mount RailsAdmin::Engine => '/kartr-admin', :as => 'rails_admin'

  get "instagram/index"

  get "instagram/new"

  get "javascripts/maps"

  get "/om-kartr" => "pages#about", as: :pages_about
  get "/anvandarvillkor" => "pages#terms", as: :pages_terms
  get "/sekretess" => "pages#privacy", as: :pages_privacy
  get "/hjalp" => "pages#help", as: :pages_help

  get "/api" => "pages#api", as: :pages_api

  match "javascripts/maps.:format" => "javascripts#maps"
  match "/api/v1/:api_key.:format" => "maps#embed", as: :embed

  devise_for :users, controllers: {
    omniauth_callbacks: "authentications",
    registrations: "registrations"
  }

  devise_scope :user do
    delete "/logga-ut" => "devise/sessions#destroy", as: :destroy_user_session
    get "/ny-bekraftelse" => "devise/confirmations#new", as: :new_user_confirmation
    get "/nytt-losenord" => "devise/passwords#new", as: :new_user_password
    get "/registrering" => "registrations#new", as: :new_user_registration
    get "/redigera-profil" => "registrations#edit", as: :edit_user_registration

    get "/users/auth/:provider" => "authentications#passthru"
  end
  get "/search" => "maps#search", as: :maps_search

  get "/searches/search"
  get "/kartor/resultat/:query" => "searches#result", as: :search_result
  get "/searches/autocomplete"

  scope(path_names: { new: "ny", edit: "redigera" }) do

    resources :home, only: [ :index ], path: "hem"

    resources :dashboard, only: [ :index ], path: "startsida"

    resources :profiles, only: [], path: '' do
      get "show_maps", path: "kartlista"

      resources :maps, except: [ :index ], path: "kartor" do

        resources :marks, only: [ :new, :edit, :create ], path: "markeringar"
      end
    end

    resources :profiles, only: [ :index ], path: "profiler"
    resources :profiles, only: [ :show ], path: "profil"

    resources :maps, only: [ :index ], path: "kartor" do
      post "toggle"

      resources :marks, path: "markeringar"

      resources :status_updates, only: [ :create ], path: "skapa-uppdatering"
      resources :map_comments, only: [ :create ], path: "skapa-kommentar"
    end

    resources :map_comments, only: [ :update, :destroy ], path: "kart-kommentarer" do
      post "toggle_like"
    end

    resources :status_updates, only: [ :update, :destroy ], path: "status-uppdateringar" do
      post "toggle_like"

      resources :status_comments, only: [ :create ], path: "kommentarer"
    end

    resources :status_comments, only: [ :update, :destroy ], path: "status-kommentarer" do
      post "toggle_like"
    end

    resources :marks, only: [ :update, :destroy ], path: "markeringar"

  end

  root to: "home#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :scoped, scope: :user

  ## Skapa api nyckel
  before_create :generate_api_key
  before_destroy { tags.clear }
  # before_save :validate_tags

  belongs_to :user
  belongs_to :location

  has_and_belongs_to_many :tags, uniq: true


  has_many :marks, dependent: :destroy
  has_many :status_updates, order: "created_at DESC", dependent: :destroy
  has_many :map_comments, order: "created_at DESC", dependent: :destroy

  acts_as_followable
  acts_as_gmappable

  accepts_nested_attributes_for :location

  MAP_TYPES = [ "HYBRID", "ROADMAP", "SATELLITE", "TERRAIN"]
  MAX_TAG_COUNT = 5
  MAX_TAG_LENGTH = 20

  attr_accessor :longitude, :latitude
  attr_accessible :name, :description, :private, :zoom, :map_type, :location_attributes, :tag_list

  validates	:name, presence: true, length: { maximum: 50 }
  validates	:description, length: { maximum: 15360 }
  validates :private, inclusion: { in: [true, false] }
  validates :map_type, inclusion: MAP_TYPES
  validates :zoom, numericality: { only_integer: true }
  validate :validate_tags

  def follow(user)
    @follower = Follower.new()
    @follower.save
  end

  def longitude
    self.location.longitude
  end

  def latitude
    self.location.latitude
  end

  def tag_match_count(words)
    # Loopa igenom words
    @intersection = self.tags.map(&:word) & words
    return @intersection.size

    # kontrollera hur många gånger word finns i sina taggar
    # ++match
  end
  def tag_list
    self.tags.map(&:word).join(', ')
  end

  def tag_list=(words)
    self.tags = words.split(',').map do |word|
                      # Tar bort alla mellanslag
      Tag.where(word: word.gsub(/\s+/, "")).first_or_initialize
    end
  end

  ## Genererar en API nyckel på alla nya kartor.  - alla nycklar blir unika.
  def generate_api_key
    begin
      @api_key = SecureRandom.urlsafe_base64
    end while Map.where(api_key: @api_key).exists?
    self.api_key = @api_key
  end
  def comment_count
    self.map_comments.count
  end

  def follow_count
    self.followers('User').count
  end

  def status_count
    self.status_updates.count
  end

  def self.search_for(query)
    self.where("name like ?", "%#{query}%").all
  end

  def self.build_default_map
    return Map.new do |map|
      map.location = Location.new do |l|
        l.latitude = 60.0
        l.longitude = 15.0
      end
      map.map_type = "ROADMAP"
      map.zoom = 5
    end
  end
  

  private
  def validate_tags
    if self.tags.size > MAX_TAG_COUNT
      errors.add(:tag_list, I18n.t("maps.max_tag_count_reached", max: MAX_TAG_COUNT))
    end
    if self.tags.present?
      self.tags.each do |tag|
        if tag.word.length > MAX_TAG_LENGTH
          errors.add(:tag_list, I18n.t("maps.max_tag_length_reached", max: MAX_TAG_LENGTH))
        end
      end
    end
  end
end

app/controllers/maps_controller.rb
require File.dirname('') + '/config/environment.rb'
class MapsController < ApplicationController
  autocomplete :map, :name, extra_data: [:description, :user_id]
  before_filter :authenticate_user!
  ## Skippa validering på embeddade kartor.
  skip_before_filter :authenticate_user!, only: ['embed', 'show']

  def index
    ## Hämtar alla kartor användaren äger
    @maps = Map.order("created_at ASC").find_all_by_user_id(current_user.id)
    render json: Tag.all, only: [:id, :word, :description, :slug, :user_id, :map_views]
  end

  def toggle
    @map = Map.find(params[:map_id])
    if current_user.follows?(@map)
      current_user.unfollow!(@map)
    else
      current_user.follow!(@map)
    end
    render template: 'maps/follow/toggle'
  end

  def show
    begin
      # Hämtar användaren som äger kartan för att filtrera
      @user = User.find(params[:profile_id])

      @current_user = current_user

      # Hämtar rätt karta från användarens samling
      @map = @user.maps.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render template: 'maps/404', status: 404
      return
    end

    #Nya objekt som kan skapas på maps-sidan
    @status_update = StatusUpdate.new
    @status_comment = StatusComment.new
    @map_comment = MapComment.new

    # Kontrollerar om användaren har behörighet att titta på kartan.
    if @map.private? and @map.user != current_user
      flash[:error] = t :private, scope: [:maps]
      render template: 'maps/show_private.html.erb'
      return
    end

    ## Räkna sidvisningar på kartan, men inte på egna kartor.
    if @map.user.id != current_user.id
      @map.increment :map_views
      @map.save
    end

    display_map(@map)
  end

  def new
    # skapar ett map-objekt med default-data och ett sätter map-location till default
    @map = Map.build_default_map

    display_map(@map)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: {map: @map, display_map: @display_map }}
    end
  end

  def create
    # Tar bort IDt från en tidigare sparad location (om valideringen failats)
    # Tar man bort denna rad kastas undantag för det inte går att assiciera en 
    # redan befintlig location med ett objekt som inte än är skapad (kartan)
    params[:map][:location_attributes][:id] = nil

    @map = Map.new(params[:map]) do |m|
      m.user = current_user
      m.location = Location.find_by_latitude_and_longitude(m.latitude, m.longitude) || m.location
    end

    if @map.save
      flash[:success] = t :created, map: @map.name, scope: [:maps]
      redirect_to profile_map_path(@map.user.slug, @map.slug)
    else
      display_map(@map)
      flash[:error] = t :failed_to_create, scope: [:maps]
      render action: :new
    end

  end

  # GET profiles/:username/maps/:slug/edit
  def edit
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    display_map(@map)
    unless current_user == @map.user
      flash[:error] = t :access_denied
      redirect_to profile_map_path(@user.slug, @map.slug)
    end
  end

  # PUT /maps/:id/
  def update
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    # Sparar undan sluggen om namn-fältet är tomt
    @slug = @map.slug

    display_map(@map)
    if current_user == @map.user
      if @map.update_attributes(params[:map])
        @map.location = Location.find_or_create_by_latitude_and_longitude(@map.latitude, @map.longitude)

        if not request.xhr?
          flash[:success] = t :updated, map: @map.name, scope: [:maps]
        end

        redirect_to profile_map_path(@map.user.slug, @map.slug)
      else
        if not request.xhr?
          flash[:error] = t :failed_to_update, scope: [:maps]
        end

        render action: :edit
      end
    else
      if not request.xhr?
        flash[:error] = t :access_denied
      end

      redirect_to profile_map_path(@map.user.slug, @map.slug)
    end
  end

  def destroy
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    @map_name = @map.name
    if current_user == @map.user
      if @map.destroy
        flash[:success] = t :removed, map: @map_name, scope: [:maps]
      else
        flash[:error] = t :failed_to_remove, scope: [:maps]
      end
    else
      flash[:error] = t :access_denied
    end
    redirect_to root_path
  end

  # Sets options for map
  def display_map(map)

    @display_map = {
        map_options: {
            auto_adjust: false,
            type: map.map_type,
            zoom: map.zoom,
            center_latitude: map.latitude,
            center_longitude: map.longitude,
            raw: "{ scrollwheel: false }"
        },
        markers: {
          data: map.marks.to_gmaps4rails  do |mark, marker|
            # Rendera en partial i infofönstret
            marker.infowindow(render_to_string(partial: "marks/foobar",  locals: { mark: mark}))

            # ändra markeringens bild
            marker.picture({
                            picture: "/assets/icons/marker-001.png",
                            width: 32,
                            height: 32
                           })
            # Titeln
            marker.title(mark.name)
            # Sidebar - inte implementerat
            #marker.sidebar "i'm the sidebar"
            # Om man vill lägga till fler fält till markeringen i jsonformat
            marker.json({ id: mark.id, foo: "bar" })
          end
        }
    }
  end



  ### UNDER UTVECKLING!
  ### ANVÄND EJ!
  ### PILLA INTE SÖNDER KOD!
  ### EJ SLUTGILTLIG VERSION!
  ## ------------------------------

  ## Genererar en karta utifrån angiven API-nyckel
  def embed
    ## Beroende
    require 'json'
    ## API nyckel
    key = params[:api_key]
    ## Standard värden för höj bredd och enhet samt karttyp.
    if(params.has_key?(:width))
      @width = params[:width]
    else
      @width = '100'
    end

    if(params.has_key?(:height))
      @height = params[:height]
    else
      @height = '100'
    end

    if(params.has_key?(:unit))
      @unit = params[:unit]
    else
      @unit = '%'
    end

    if(params.has_key?(:mapType))
      @map_type = params[:mapType]
    else
      @map_type = 'ROADMAP'
    end
    ## Hämtar aktuell karta.
    @embed_map = Map.find_by_api_key(key)

    if @embed_map.private?
      output = {'error' => 'Kan ej badda in privata kartor.'}.to_json
      render :json => output
      return
    end
    ## Map i json
    @map = @embed_map.to_json

    ## Göra om koordinater till korrekt json
    @marks = @embed_map.marks.to_gmaps4rails

    ## Locations i JSON
    @location = @embed_map.location.to_json


    respond_to do |format|
      format.html { render :html => {:map => @map,
                                     :marks => @marks,
                                     :location => @location}, :layout => false }

      format.json { render :json =>  {:map => @map,
                                      :marks => @marks,
                                      :location => @location} }
    end


    ##render :layout => false
  end
end

app/helpers/maps_helper.rb
module MapsHelper

  def first_map?
    return current_user.maps.count === 0
  end
end

app/views/maps/shared/_comment_count.html.erb
<span class="counter"><%= @map.comment_count %></span>
<span>kommentarer</span>

app/views/maps/shared/_display_tags.html.erb
<% if @map.tag_list.present? %>
	<dl class="map-tags">
      <dd class="subheader">Taggar: </dd>
	  <% @map.tags.each do |t| %>
	  	<dd><span class="round label"><%= link_to t.word, search_result_path(t.word) %></span></dd>
	  <% end %>
	</dl>
<% else %>
  <span class="">Inga taggar än.</span>
<% end %>

app/views/maps/shared/_first_map_greeting.html.erb
<li data-button="Börja">
  <% if current_user.sign_in_count === 1 %>
      <h5 class="tip-header">Hej och välkommen till Kartr.se!</h5>
      <p class="tip-body">
        Vad kul att du ville prova vår karttjänst. För att hjälpa dig att komma igång finns det här en genomgång av hur det går till när du skapar din första karta.
        Om du inte vill ta del av vår hjälp stänger du bara denna ruta, annars klickar du på "börja" och följ instruktionerna så har du snart din första karta klar, lycka till!</p>
      </p>
  <% elsif first_map? %>
      <h5 class="tip-header">Detta verkar vara din första karta!</h5>
      <p class="tip-body">För att hjälpa dig att komma igång finns det här en genomgång av hur det går till när du skapar din första karta.
        Bara stäng denna ruta om du inte prova själv eller klicka på "börja" och följ instruktionerna så har du snart din första karta klar.
      </p>
      <h6>lycka till!</h6>
  <% end %>
</li>

app/views/maps/shared/_follow_button.html.erb
<div id="follow-button">
<% if current_user.follows?(@map) %>
    <%= link_to 'Sluta följ', map_toggle_path(@map.id), { :method => :post,:remote => true, :class => 'alert small button radius'} %>
  <% else %> 
    <%= link_to 'Följ', map_toggle_path(@map.id), { :method => :post,:remote => true, :class => 'small button radius'} %>
<% end %>
</div>

app/views/maps/shared/_follow_count.html.erb
<span class="counter"><%= @map.follow_count %></span>
<span class="counter-text">följare</span>

app/views/maps/shared/_form.html.erb
<% if @map.errors.messages[:name].present? %>
    <%= f.label :name, "Namn på kartan", class: 'error' %>
    <%= f.text_field :name, autofocus: true, class: 'error' %>
    <small class="error"><%= @map.errors.messages[:name].first %></small>
<% else %>
    <%= f.label :name, "Namn på kartan" %>
    <%= f.text_field :name, autofocus: true %>
<% end %>

<% if @map.errors.messages[:description].present? %>
    <%= f.label :description, "Beskrivning", class: 'error'  %>
    <%= f.text_area :description, size: "30x8", class: 'error'  %>
    <small class="error"><%= @map.errors.messages[:description].first %></small>
<% else %>
    <%= f.label :description, "Beskrivning" %>
    <%= f.text_area :description, size: "30x8" %>
<% end %>


<% if @map.errors.messages[:tag_list].present? %>
    <%= f.label :tag_list, "Tagga din karta med sökord! (max 5st)", class: 'error'  %>
    <ul id="myTags">
</ul>
    <%= f.hidden_field :tag_list, class: 'error'  %>
    <small class="error"><%= @map.errors.messages[:tag_list].first %></small>
<% else %>
    <%= f.label :tag_list, "Tagga din karta med sökord! (max 5st)" %>
    <ul id="myTags">
</ul>
    <%= f.hidden_field :tag_list%>
<% end %>

<div id="map-private">
  <%= f.label :private, "Vem ska få se kartan?" %>
  <%= f.radio_button :private, true, { checked: @map.private } %> Privat <br />
  <%= f.radio_button :private, false, { checked: !@map.private } %> Publik
</div>

<div class="field">

  <%= f.fields_for :location do |location_fields| %>
      <%= location_fields.hidden_field :latitude, value: @map.latitude, id: "center-lat" %>
      <%= location_fields.hidden_field :longitude, value: @map.longitude, id: "center-lng" %>
  <% end %>
  <%= f.hidden_field :zoom, id: "map-zoom" %>
  <%= f.hidden_field :map_type, id: "map-type" %>
</div>
<div class="submit-button"><%= f.submit "Spara karta", class: "button", id: "saveMapButton" %></div>

app/views/maps/shared/_list_marks.html.erb
<% if ( @map.marks.present? ) %>
    <% ( @map.marks ).each do |mark| %>
        <li class="mark-links">
          <a data-markid="<%= mark.id %>" class="mark-link" href="#">
              <span class="has-tip" title="<%= mark.description %>">
                <%= mark.name %>
              </span>
          </a>
          <% if mark.map.user === current_user or mark.user === current_user %>
          <span class="link-icons">
              <%= link_to raw('<i class="foundicon-trash general"></i>'), mark_path(mark), title: "ta bort markering", method: :delete, class: "right delete-mark", remote: true %>
              <%= link_to raw('<i class="foundicon-edit large"></i>'), edit_profile_map_mark_path(mark.map.user.slug, mark.map.slug, mark), title: "Redigera markering", class: "right edit-mark" %>
            </span>
          <% end %>
          <hr>
        </li>
    <% end %>
<% else %>
    <li>Inga markeringar än.</li>
<% end %>

app/views/maps/shared/_map_tutorial.html.erb
<ol id="map-tutorial">

    <%= render 'maps/shared/first_map_greeting' %>
  <!-- Kartans namn -->
  <li data-id="map_name" data-button="nästa">
    <h5 class="tip-header">Kartans namn</h5>
    <p class="tip-body">Namnet är obligatoriskt och kan innehålla upp till 50 tecken. Det går att ändra namnet vid ett senare tillfälle om du önskar.
      <span class="tip-footer">
        <span class="tip-tips">Tips:</span> Skriv ett namn som relaterar till kartans innehåll för att underlätta för de användare som kommer besöka din karta.</span>
    </p>
  </li>

  <!-- Beskrivningen -->
  <li data-id="map_description" data-button="nästa">
    <h5 class="tip-header">Beskrivning av kartan</h5>
    <p class="tip-body">Beskrivningen kan vara väldigt lång om du så vill, den är inget måste men vi rekommenderar ändå att du skriver lite kort om vad du tänkt dig med din karta för att underlätta för dina besökare.
      Precis som med namnet kan du redigera beskrivningen efterhand som innehållet kommer att uppdateras.
      <span class="tip-footer">
        <span class="tip-tips">Tips:</span> Skriv en beskrivning som relaterar till kartans innehåll. Håll din beskrivning uppdaterad med innehållet på kartan</span>
    </p>
  </li>

  <!-- Taggar -->
  <li data-id="myTags" data-button="nästa">
    <h5 class="tip-header">Lägg till taggar på kartan</h5>
    <p class="tip-body">Taggarna är först och främst till för sökningen av kator och fungerar då som sökord. En karta kan max ha 5 taggar och de bör beskriva din karta och dess innehåll för att underlätta för dina besökare.
      Precis som med namn och beskrivning kan du byta ut taggar efterhand som innehållet kommer att uppdateras.
      <span class="tip-footer">
        <span class="tip-tips">Tips:</span> Skriv taggar som relaterar till kartans innehåll. Håll dina taggar uppdaterad med innehållet på kartan</span>
    </p>
  </li>

  <!-- Privat -->
  <li data-id="map-private" data-button="nästa">
    <h5 class="tip-header">Gör din karta privat</h5>
    <p class="tip-body">Att göra din karta privat innebär att bara de som blir inbjudna får tillgång till kartan.
      De publika kartorna kan ses av alla på Kartr.se
      <span class="tip-footer">
        <span class="tip-tips">Tips:</span> Privata kartor kan vara bra till grupper med gemensamma intressen som: sport, resor, festivaler och andra musikhändelser osv.</span>
    </p>
  </li>

  <!-- Kartan -->
  <li data-id="map-options" data-options="tipLocation:right;" data-button="klar!">
    <h5 class="tip-header">Så över till själva kartan</h5>
    <p class="tip-body">Kartan är centrerad runt Sverige till en början men det är nu upp till dig att ställa in ett eget område.
      Du behöver först sätta ett området din karta ska täcka. Ställ sedan in zoomen på kartan till önskat läge.
      <span class="tip-footer">
        <span class="tip-tips">Tips:</span> Tänk på att kartans zoom sparas i det läge du valt så vilket sätt du än använt för att hitta en position kan du fortfarande zooma ut om du vill att din karta ska täcka ett större område.</span>
      Det finns tre olika sett att hitta en position:
    </p>
    <ol>
      <li>"Hitta min position" - Här kommer din karta att centreras runt den position du för tillfället befinner dig på.</li>
      <li>Sök startposition - Här hittar du positioner genom att söka på ex. städer och adresser</li>
      <li>Använd kartan - När du ändrar på kartan kommer även centrumpositionen att ändra sig så ställ in kartan som du vill.</li>
    </ol>
  </li>
</ol>

<% content_for :end_of_body do %>
    <!-- Startar foundations joyride till tutorial:en  -->
    <script>
        $(window).load(function() {
            $("#map-tutorial").joyride({
                tipLocation: 'left',
                Animation:'pop',
                postStepCallback: function(index) {
                    var targetTip = index + 1;
                    var targetInput = '';

                    if (targetTip === 1) {
                        targetInput =  '#map_name';

                    }
                    else if(targetTip === 2) {
                        targetInput =  '#map_description';
                    }
                    else if(targetTip === 3) {
                        targetInput =  '#myTags li input[type=text]';
                    }
                    else if(targetTip === 5) {
                        targetInput =  '#locationTextField';
                    }
                    else if (targetTip === 6) {
                        targetInput =  '#saveMapButton';
                    }
                    map_private_false
                    $(targetInput).focus();
                    console.log(targetTip);
                }
            });
        });
    </script>
<% end %>

app/views/maps/shared/_my_maps.html.erb
<section id="my-maps">
  <h4 class="subheader"><%= @user.name || @user.username %>'s kartor</h4>
  
<% if @user.maps.any? %>
 <table class="twelve table-maps">
    <thead>
      <tr>
        <th>Namn</th>
        <th>Taggar</th>
        <th>Följare</th>
        <th>Markeringar</th>
        <th>Statusuppdateringar</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @maps.each do |map| %>
      <% unless current_user === @user %>
        <% unless map.private? %>
        <tr>
          <td>
            <span class="has-tip tip-bottom radius" data-width="100" title="<%= map.description %>">
              <%= link_to map.name, profile_map_path(map.user.slug, map.slug) %>
            </span>  
          </td>
          <td>
            <% map.tags.each do |t| %>
              <span class=""><%= link_to t.word, search_result_path(t.word) %></span>  
            <% end %>
          </td>
          <td><span class="counter"><%= map.follow_count %></span></td>
          <td><span class="counter"><%= map.marks.count %></span></td>
          <td><span class="counter"><%= map.status_count %></span></td>
          <td></td>
        </tr>
        <% end %>
      <% else %> 
      <tr>
        <td>
          <span class="has-tip tip-bottom radius" data-width="100" title="<%= map.description %>">
            <%= link_to map.name, profile_map_path(map.user.slug, map.slug) %>
          </span>  
        </td>
        <td>
          <% map.tags.each do |t| %>
            <span class=""><%= link_to t.word, search_result_path(t.word) %></span>  
          <% end %>
        </td>
        <td><span class="counter"><%= map.follow_count %></span></td>
        <td><span class="counter"><%= map.marks.count %></span></td>
        <td><span class="counter"><%= map.status_count %></span></td>
        <td class="link-icons">
          <%= link_to raw("<i class='foundicon-edit'></i>"), edit_profile_map_path(map.user.slug, map.slug) %>
          <%= link_to raw("<i class='foundicon-trash'></i>"), profile_map_path(map.user.slug, map.slug), 
              :method => :delete, :confirm => "Vill du ta bort kartan?" %>
          <% if map.private %>
          <span class="has-tip tip-bottom radius" data-width="80" title="Privat karta"><i class="foundicon-lock"></i></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Tyvärr, användaren har inga kartor än.</p>
<% end %>

<% if current_user === @user %>
    <div class="row">
      <div class="twelve columns">
        <%= link_to "Ny karta", new_profile_map_path(current_user.slug), class: "button" %>
      </div>
    </div>
<% end %>
</section>

app/views/maps/shared/_status_count.html.erb
<span class="counter"><%= @map.status_count %></span>
<span class="counter-text">statusar</span>