config/routes.rb
Wp102dv401::Application.routes.draw do

  mount RailsAdmin::Engine => '/kartr-admin', :as => 'rails_admin'

  get "instagram/index"

  get "instagram/new"

  get "javascripts/maps"

  get "/om-kartr" => "pages#about", as: :pages_about
  get "/anvandarvillkor" => "pages#terms", as: :pages_terms
  get "/sekretess" => "pages#privacy", as: :pages_privacy
  get "/hjalp" => "pages#help", as: :pages_help

  get "/api" => "pages#api", as: :pages_api

  match "javascripts/maps.:format" => "javascripts#maps"
  match "/api/v1/:api_key.:format" => "maps#embed", as: :embed

  devise_for :users, controllers: {
    omniauth_callbacks: "authentications",
    registrations: "registrations"
  }

  devise_scope :user do
    delete "/logga-ut" => "devise/sessions#destroy", as: :destroy_user_session
    get "/ny-bekraftelse" => "devise/confirmations#new", as: :new_user_confirmation
    get "/nytt-losenord" => "devise/passwords#new", as: :new_user_password
    get "/registrering" => "registrations#new", as: :new_user_registration
    get "/redigera-profil" => "registrations#edit", as: :edit_user_registration

    get "/users/auth/:provider" => "authentications#passthru"
  end
  get "/search" => "maps#search", as: :maps_search

  get "/searches/search"
  get "/kartor/resultat/:query" => "searches#result", as: :search_result
  get "/searches/autocomplete"

  scope(path_names: { new: "ny", edit: "redigera" }) do

    resources :home, only: [ :index ], path: "hem"

    resources :dashboard, only: [ :index ], path: "startsida"

    resources :profiles, only: [], path: '' do
      get "show_maps", path: "kartlista"

      resources :maps, except: [ :index ], path: "kartor" do

        resources :marks, only: [ :new, :edit, :create ], path: "markeringar"
      end
    end

    resources :profiles, only: [ :index ], path: "profiler"
    resources :profiles, only: [ :show ], path: "profil"

    resources :maps, only: [ :index ], path: "kartor" do
      post "toggle"

      resources :marks, path: "markeringar"

      resources :status_updates, only: [ :create ], path: "skapa-uppdatering"
      resources :map_comments, only: [ :create ], path: "skapa-kommentar"
    end

    resources :map_comments, only: [ :update, :destroy ], path: "kart-kommentarer" do
      post "toggle_like"
    end

    resources :status_updates, only: [ :update, :destroy ], path: "status-uppdateringar" do
      post "toggle_like"

      resources :status_comments, only: [ :create ], path: "kommentarer"
    end

    resources :status_comments, only: [ :update, :destroy ], path: "status-kommentarer" do
      post "toggle_like"
    end

    resources :marks, only: [ :update, :destroy ], path: "markeringar"

  end

  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: [:slugged, :history]

  has_many :status_updates, dependent: :destroy
  has_many :status_comments, dependent: :destroy
  has_many :maps, dependent: :destroy
  has_many :marks, dependent: :destroy

  acts_as_follower
  acts_as_liker

  # To use devise-twitter don't forget to include the :twitter_oauth module:

  # e.g. devise :database_authenticatable, ... , :twitter_oauth
  # IMPORTANT: If you want to support sign in via twitter you MUST remove the
  # :validatable module, otherwise the user will never be saved
  # since it's email and password is blank.
  # :validatable checks only email and password so it's safe to remove
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, authentication_keys: [:login]

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field remote 'username'
  attr_accessor :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
                  :remember_me, :provider, :uid, :username,
                  :name, :login, :profile_image, :likes

  validates_uniqueness_of :username
  validates_uniqueness_of :email, case_sensitive: false, allow_blank: true

  ## Ser till att e-post inte behövs vid Twitter registrering.
  def email_required?
    super && provider.blank?
  end

  # Lägger till facebook-mailen till användarkontot när det registreras
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Hittar användare eller registrerar en ny
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.extra.raw_info.username,
          provider: auth.provider,
          uid: auth.uid,
          profile_image: auth.info.image,
          email: auth.info.email,
          password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save
    end
    return user
  end


  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # Fullösning. Fixa
    nummer = rand(1+1000)+1000
    foonummer = nummer.to_s << "@gmail.com"


    unless user
      user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname,
          provider: auth.provider,
          uid: auth.uid,
          profile_image: auth.info.image,
          password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save
    end

    return user
  end

  # function to handle user's login via email or username
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.search_for(query)
    self.where("username like ?", "%#{query}%").all
  end

  def skip_confirmation!
    self.confirmed_at = Time.now
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Logga in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrera dig", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Glömt ditt lösenord?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Fick du inga bekräftelseinstruktioner?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Fick du inga upplåsningsinstruktioner?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Logga in med #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_login_form.html.erb
<fieldset class="loggin-fieldset">
  <legend>Logga in</legend>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="login">
        <%# f.label :login, "Epost eller användarnamn" %>
        <%= f.text_field :login, placeholder: "Epost eller användarnamn" %>
      </div>

      <div class="password">
        <%# f.label :password, "Lösenord" %>
        <%= f.password_field :password, placeholder: "Lösenord" %>
      </div>

      <% if devise_mapping.rememberable? -%>
          <div><%= f.check_box :remember_me, class: "remember-me" %> <%= f.label :remember_me, "Kom ihåg mig", class: "remember-me" %></div>
      <% end -%>

      <div><%= f.submit "Logga in", class: "right button loggin" %></div>
  <% end %>
</fieldset>
<fieldset class="loggin-fieldset">
  <legend> Använd eget konto </legend>
  <div class="account-login">
    <%= link_to image_tag("login_with_facebook.png", alt: "logga in med facebook"), user_omniauth_authorize_path(:facebook), title: "Logga in med facebook" %>
  </div>
</fieldset>