config/routes.rb
Wp102dv401::Application.routes.draw do

  mount RailsAdmin::Engine => '/kartr-admin', :as => 'rails_admin'

  get "instagram/index"

  get "instagram/new"

  get "javascripts/maps"

  get "/om-kartr" => "pages#about", as: :pages_about
  get "/anvandarvillkor" => "pages#terms", as: :pages_terms
  get "/sekretess" => "pages#privacy", as: :pages_privacy
  get "/hjalp" => "pages#help", as: :pages_help

  get "/api" => "pages#api", as: :pages_api

  match "javascripts/maps.:format" => "javascripts#maps"
  match "/api/v1/:api_key.:format" => "maps#embed", as: :embed

  devise_for :users, controllers: {
    omniauth_callbacks: "authentications",
    registrations: "registrations"
  }

  devise_scope :user do
    delete "/logga-ut" => "devise/sessions#destroy", as: :destroy_user_session
    get "/ny-bekraftelse" => "devise/confirmations#new", as: :new_user_confirmation
    get "/nytt-losenord" => "devise/passwords#new", as: :new_user_password
    get "/registrering" => "registrations#new", as: :new_user_registration
    get "/redigera-profil" => "registrations#edit", as: :edit_user_registration

    get "/users/auth/:provider" => "authentications#passthru"
  end
  get "/search" => "maps#search", as: :maps_search

  get "/searches/search"
  get "/kartor/resultat/:query" => "searches#result", as: :search_result
  get "/searches/autocomplete"

  scope(path_names: { new: "ny", edit: "redigera" }) do

    resources :home, only: [ :index ], path: "hem"

    resources :dashboard, only: [ :index ], path: "startsida"

    resources :profiles, only: [], path: '' do
      get "show_maps", path: "kartlista"

      resources :maps, except: [ :index ], path: "kartor" do

        resources :marks, only: [ :new, :edit, :create ], path: "markeringar"
      end
    end

    resources :profiles, only: [ :index ], path: "profiler"
    resources :profiles, only: [ :show ], path: "profil"

    resources :maps, only: [ :index ], path: "kartor" do
      post "toggle"

      resources :marks, path: "markeringar"

      resources :status_updates, only: [ :create ], path: "skapa-uppdatering"
      resources :map_comments, only: [ :create ], path: "skapa-kommentar"
    end

    resources :map_comments, only: [ :update, :destroy ], path: "kart-kommentarer" do
      post "toggle_like"
    end

    resources :status_updates, only: [ :update, :destroy ], path: "status-uppdateringar" do
      post "toggle_like"

      resources :status_comments, only: [ :create ], path: "kommentarer"
    end

    resources :status_comments, only: [ :update, :destroy ], path: "status-kommentarer" do
      post "toggle_like"
    end

    resources :marks, only: [ :update, :destroy ], path: "markeringar"

  end

  root to: "home#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :scoped, scope: :user

  ## Skapa api nyckel
  before_create :generate_api_key
  before_destroy { tags.clear }
  # before_save :validate_tags

  belongs_to :user
  belongs_to :location

  has_and_belongs_to_many :tags, uniq: true


  has_many :marks, dependent: :destroy
  has_many :status_updates, order: "created_at DESC", dependent: :destroy
  has_many :map_comments, order: "created_at DESC", dependent: :destroy

  acts_as_followable
  acts_as_gmappable

  accepts_nested_attributes_for :location

  MAP_TYPES = [ "HYBRID", "ROADMAP", "SATELLITE", "TERRAIN"]
  MAX_TAG_COUNT = 5
  MAX_TAG_LENGTH = 20

  attr_accessor :longitude, :latitude
  attr_accessible :name, :description, :private, :zoom, :map_type, :location_attributes, :tag_list

  validates	:name, presence: true, length: { maximum: 50 }
  validates	:description, length: { maximum: 15360 }
  validates :private, inclusion: { in: [true, false] }
  validates :map_type, inclusion: MAP_TYPES
  validates :zoom, numericality: { only_integer: true }
  validate :validate_tags

  def follow(user)
    @follower = Follower.new()
    @follower.save
  end

  def longitude
    self.location.longitude
  end

  def latitude
    self.location.latitude
  end

  def tag_match_count(words)
    # Loopa igenom words
    @intersection = self.tags.map(&:word) & words
    return @intersection.size

    # kontrollera hur många gånger word finns i sina taggar
    # ++match
  end
  def tag_list
    self.tags.map(&:word).join(', ')
  end

  def tag_list=(words)
    self.tags = words.split(',').map do |word|
                      # Tar bort alla mellanslag
      Tag.where(word: word.gsub(/\s+/, "")).first_or_initialize
    end
  end

  ## Genererar en API nyckel på alla nya kartor.  - alla nycklar blir unika.
  def generate_api_key
    begin
      @api_key = SecureRandom.urlsafe_base64
    end while Map.where(api_key: @api_key).exists?
    self.api_key = @api_key
  end
  def comment_count
    self.map_comments.count
  end

  def follow_count
    self.followers('User').count
  end

  def status_count
    self.status_updates.count
  end

  def self.search_for(query)
    self.where("name like ?", "%#{query}%").all
  end

  def self.build_default_map
    return Map.new do |map|
      map.location = Location.new do |l|
        l.latitude = 60.0
        l.longitude = 15.0
      end
      map.map_type = "ROADMAP"
      map.zoom = 5
    end
  end
  

  private
  def validate_tags
    if self.tags.size > MAX_TAG_COUNT
      errors.add(:tag_list, I18n.t("maps.max_tag_count_reached", max: MAX_TAG_COUNT))
    end
    if self.tags.present?
      self.tags.each do |tag|
        if tag.word.length > MAX_TAG_LENGTH
          errors.add(:tag_list, I18n.t("maps.max_tag_length_reached", max: MAX_TAG_LENGTH))
        end
      end
    end
  end
end

app/controllers/maps_controller.rb
require File.dirname('') + '/config/environment.rb'
class MapsController < ApplicationController
  autocomplete :map, :name, extra_data: [:description, :user_id]
  before_filter :authenticate_user!
  ## Skippa validering på embeddade kartor.
  skip_before_filter :authenticate_user!, only: ['embed', 'show']

  def index
    ## Hämtar alla kartor användaren äger
    @maps = Map.order("created_at ASC").find_all_by_user_id(current_user.id)
    render json: Tag.all, only: [:id, :word, :description, :slug, :user_id, :map_views]
  end

  def toggle
    @map = Map.find(params[:map_id])
    if current_user.follows?(@map)
      current_user.unfollow!(@map)
    else
      current_user.follow!(@map)
    end
    render template: 'maps/follow/toggle'
  end

  def show
    begin
      # Hämtar användaren som äger kartan för att filtrera
      @user = User.find(params[:profile_id])

      @current_user = current_user

      # Hämtar rätt karta från användarens samling
      @map = @user.maps.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      render template: 'maps/404', status: 404
      return
    end

    #Nya objekt som kan skapas på maps-sidan
    @status_update = StatusUpdate.new
    @status_comment = StatusComment.new
    @map_comment = MapComment.new

    # Kontrollerar om användaren har behörighet att titta på kartan.
    if @map.private? and @map.user != current_user
      flash[:error] = t :private, scope: [:maps]
      render template: 'maps/show_private.html.erb'
      return
    end

    ## Räkna sidvisningar på kartan, men inte på egna kartor.
    if @map.user.id != current_user.id
      @map.increment :map_views
      @map.save
    end

    display_map(@map)
  end

  def new
    # skapar ett map-objekt med default-data och ett sätter map-location till default
    @map = Map.build_default_map

    display_map(@map)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: {map: @map, display_map: @display_map }}
    end
  end

  def create
    # Tar bort IDt från en tidigare sparad location (om valideringen failats)
    # Tar man bort denna rad kastas undantag för det inte går att assiciera en 
    # redan befintlig location med ett objekt som inte än är skapad (kartan)
    params[:map][:location_attributes][:id] = nil

    @map = Map.new(params[:map]) do |m|
      m.user = current_user
      m.location = Location.find_by_latitude_and_longitude(m.latitude, m.longitude) || m.location
    end

    if @map.save
      flash[:success] = t :created, map: @map.name, scope: [:maps]
      redirect_to profile_map_path(@map.user.slug, @map.slug)
    else
      display_map(@map)
      flash[:error] = t :failed_to_create, scope: [:maps]
      render action: :new
    end

  end

  # GET profiles/:username/maps/:slug/edit
  def edit
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    display_map(@map)
    unless current_user == @map.user
      flash[:error] = t :access_denied
      redirect_to profile_map_path(@user.slug, @map.slug)
    end
  end

  # PUT /maps/:id/
  def update
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    # Sparar undan sluggen om namn-fältet är tomt
    @slug = @map.slug

    display_map(@map)
    if current_user == @map.user
      if @map.update_attributes(params[:map])
        @map.location = Location.find_or_create_by_latitude_and_longitude(@map.latitude, @map.longitude)

        if not request.xhr?
          flash[:success] = t :updated, map: @map.name, scope: [:maps]
        end

        redirect_to profile_map_path(@map.user.slug, @map.slug)
      else
        if not request.xhr?
          flash[:error] = t :failed_to_update, scope: [:maps]
        end

        render action: :edit
      end
    else
      if not request.xhr?
        flash[:error] = t :access_denied
      end

      redirect_to profile_map_path(@map.user.slug, @map.slug)
    end
  end

  def destroy
    # Hämtar användaren som äger kartan för att filtrera
    @user = User.find(params[:profile_id])

    # Hämtar rätt karta från användarens samling
    @map = @user.maps.find(params[:id])

    @map_name = @map.name
    if current_user == @map.user
      if @map.destroy
        flash[:success] = t :removed, map: @map_name, scope: [:maps]
      else
        flash[:error] = t :failed_to_remove, scope: [:maps]
      end
    else
      flash[:error] = t :access_denied
    end
    redirect_to root_path
  end

  # Sets options for map
  def display_map(map)

    @display_map = {
        map_options: {
            auto_adjust: false,
            type: map.map_type,
            zoom: map.zoom,
            center_latitude: map.latitude,
            center_longitude: map.longitude,
            raw: "{ scrollwheel: false }"
        },
        markers: {
          data: map.marks.to_gmaps4rails  do |mark, marker|
            # Rendera en partial i infofönstret
            marker.infowindow(render_to_string(partial: "marks/foobar",  locals: { mark: mark}))

            # ändra markeringens bild
            marker.picture({
                            picture: "/assets/icons/marker-001.png",
                            width: 32,
                            height: 32
                           })
            # Titeln
            marker.title(mark.name)
            # Sidebar - inte implementerat
            #marker.sidebar "i'm the sidebar"
            # Om man vill lägga till fler fält till markeringen i jsonformat
            marker.json({ id: mark.id, foo: "bar" })
          end
        }
    }
  end



  ### UNDER UTVECKLING!
  ### ANVÄND EJ!
  ### PILLA INTE SÖNDER KOD!
  ### EJ SLUTGILTLIG VERSION!
  ## ------------------------------

  ## Genererar en karta utifrån angiven API-nyckel
  def embed
    ## Beroende
    require 'json'
    ## API nyckel
    key = params[:api_key]
    ## Standard värden för höj bredd och enhet samt karttyp.
    if(params.has_key?(:width))
      @width = params[:width]
    else
      @width = '100'
    end

    if(params.has_key?(:height))
      @height = params[:height]
    else
      @height = '100'
    end

    if(params.has_key?(:unit))
      @unit = params[:unit]
    else
      @unit = '%'
    end

    if(params.has_key?(:mapType))
      @map_type = params[:mapType]
    else
      @map_type = 'ROADMAP'
    end
    ## Hämtar aktuell karta.
    @embed_map = Map.find_by_api_key(key)

    if @embed_map.private?
      output = {'error' => 'Kan ej badda in privata kartor.'}.to_json
      render :json => output
      return
    end
    ## Map i json
    @map = @embed_map.to_json

    ## Göra om koordinater till korrekt json
    @marks = @embed_map.marks.to_gmaps4rails

    ## Locations i JSON
    @location = @embed_map.location.to_json


    respond_to do |format|
      format.html { render :html => {:map => @map,
                                     :marks => @marks,
                                     :location => @location}, :layout => false }

      format.json { render :json =>  {:map => @map,
                                      :marks => @marks,
                                      :location => @location} }
    end


    ##render :layout => false
  end
end

app/helpers/maps_helper.rb
module MapsHelper

  def first_map?
    return current_user.maps.count === 0
  end
end

app/views/maps/404.html.erb
<% title "Hittades inte!" %>

<div class="row">
  <div class="twelve columns">
    <h2>Hoppsan! :(</h2>
  </div>
</div>
<div class="row">
  <div class="twelve columns">
    <p>Kartan du efterfrågade hittades inte.</p>
    <p>Du blir strax flyttad till <%= link_to 'startsidan', root_path %></p>
  </div>
</div>


<script>
  setTimeout(function() {
  window.location.href = "<%= root_path %>";
}, 5000)
</script>

app/views/maps/edit.html.erb
<% title 'Ändra i ' + @map.name %>

<!-- Header -->
<div class="row">
  <div class="twelve columns header-map">
    <h2 class="header-name">Redigera karta</h2>
  </div>
</div>

<div class="row map-main">
  <div class="nine columns">
    <!-- Map -->
    <div class="row">
      <div class="twelve columns">
        <div class="right" id="map-options"></div>
        <div class="map-wrapper">
          <%= gmaps(@display_map) %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="six columns">
        <%= text_field_tag "locationTextField", nil, placeholder: "Sök startposition" %>
      </div>
      <div class="six columns">
        <%= submit_tag "Hitta min position", type: "button", class: "right small button", id: "geolocate_button" %>
      </div>
    </div>
  </div>
  <div class="right three columns side-map">

    <div class="row">
      <div class="twelve columns">
        <% if first_map? %>
            <%= render 'maps/shared/map_tutorial' %>
        <% end %>
        <div id="mapCreation">
          <%= form_for(@map, url: profile_map_path(@map.user.slug, @map.slug), method: :put, html: { id: "map_form" }) do |f| %>
              <%= render 'maps/shared/form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/maps/embed.html.erb
<script src="http://code.jquery.com/jquery-1.9.0.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">


    /*
    EJ KOMPLETT KOD!
    PILLA EJ, NY VERSION UNDER UTVECKLING!
     */


	var $kartr_se = jQuery.noConflict();
		// DOM-Ready
		$kartr_se(document).ready(function() {
      var map_info = <%= raw(@map) %>
      var center = <%= raw(@location) %>
      var map;
      var bound = new google.maps.LatLngBounds();
      var markers = <%= raw(@marks) %>;

      console.log(map_info);
        var myOptions = {
          mapTypeId: google.maps.MapTypeId.<%= @map_type.upcase %>
        };

       map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);


      // Om kartan har markeringar, loopa ut dessa.
      if ( markers.length ) {
        for(var i in markers) {
          var myLatLng = new google.maps.LatLng(markers[i].lat, markers[i].lng);
          bound.extend(myLatLng);

          var mark = {}

          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map
          });
        }
      }
      else {
        var centerLatLng = new google.maps.LatLng(center.latitude, center.longitude);
        bound.extend(centerLatLng);
        map.setZoom(6);

        var marker = new google.maps.Marker({
          position: centerLatLng,
          map: map
        });
      }
      map.fitBounds(bound);

      // Lägger in overlayer så att man ser kartnamnet i kartan.
      var mapTitle = document.createElement('h3');
      mapTitle.style.color = '#444';
      mapTitle.innerHTML = map_info.name;

      var copyrightText = document.createElement('p');
      copyrightText.style.color = '#444';
      copyrightText.innerHTML = "&copy; kartr.se";

      map.controls[google.maps.ControlPosition.TOP_CENTER].push(mapTitle);
      map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(copyrightText);
		});

    </script>

<div id="map-canvas" style="width:<%= @width %><%= @unit%>; height:<%= @height%><%= @unit%>">

</div>

app/views/maps/index.html.erb
<!-- Presenterar alla användarens kartor -->

<%= title "Mina kartor" %>

<%= render "maps/shared/my_maps" %>

<h4><%= link_to "Ny karta", new_profile_map_path(current_user.slug) %></h4>

app/views/maps/new.html.erb
<% title "Skapa ny karta" %>

<!-- Header -->
<div class="row">
  <div class="twelve columns header-map">
    <h2 class="header-name">Ny karta</h2>
  </div>
</div>
<div class="row map-main">
  <div class="nine columns">
    <!-- Map -->
    <div class="row">
      <div class="twelve columns">
        <div class="right" id="map-options"></div>
         <div class="map-wrapper">
           <%= gmaps(@display_map) %>
         </div>
      </div>
    </div>
    <div class="row">
      <div class="six columns">
        <%= text_field_tag "locationTextField", nil, placeholder: "Sök startposition" %>
      </div>
      <div class="six columns">
        <%= submit_tag "Hitta min position", type: "button", class: "right small button", id: "geolocate_button" %>
      </div>
    </div>
  </div>
  <div class="right three columns side-map">
    <div class="row">
      <div class="twelve columns">
        <% if first_map? %>
            <%= render 'maps/shared/map_tutorial' %>
        <% end %>
        <div id="mapCreation">
          <%= form_for([current_user, @map], url: profile_maps_path, html: { id: "map-form" }) do |f| %>
              <%= render 'maps/shared/form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/maps/show.html.erb
<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
<% if @map.user == current_user %>
    <% # Visar namnet på kartan om det är ägaren som besöker den
       title @map.name
    %>
<% else %>
    <% # Annars visas :kartnamn, en karta av :användarens_namn
       title @map.name + ", en karta av " + (@map.user.name ? @map.user.name : @map.user.username)
    %>
<% end %>


<div class="row" id="page-map">

  <header class="twelve columns header-map">
      <p class="show-for-small">
         <button class='sidebar-button button secondary radius' id="sidebarButton" href="#sidebar">Extra</button>
      </p>
      <div class="row">
        <div class="nine columns">
          <h2><%= @map.name %></h2>
        </div>
        <div class="three columns hide-for-small">
        <% unless @map.user == current_user %>
          <%= render 'maps/shared/follow_button' %>
        <% end %>
        </div>
      </div>
  </header>

   <section role="main">

      <div class="row">
          <div class="twelve columns">
              <div class="map-info-wrapper">
                  <div class="map-description">
                  <p>
                    <% if @map.description.present? %>
                      <%= simple_format(@map.description) %>
                    <% else %>
                      Denna karta saknar beskrivning.
                    <% end %>
                  </p>
                  </div>
              </div>
            <div class="row">
              <div class="twelve columns">
                <%= render 'maps/shared/display_tags' %>
              </div>
            </div>
          </div>
      </div>

      <div class="row">
        <div class="twelve columns" id="viewMapContainter">
          <%= gmaps(@display_map) %>
        </div>
      </div>

    <% if @map.user == current_user %>
    <div class="row">
        <div class="eleven columns">
            <div class="status-update-form">
                <%= render 'status_updates/shared/form' %>
            </div>
        </div>
        <div class="one column tip-status hide-for-small">
          <span class="has-tip tip-right radius" data-witdh="190" title="Skriv en statusuppdatering till din karta">?</span>
        </div>
    </div>
    <% end %>

    <div class="row" id="tabs-comments">
      <div class="eleven columns">
        <dl class="tabs">
        <% if @map.status_updates.any? %>
          <dd class="active"><a href="#status">Statusuppdateringar</a></dd>
          <dd><a href="#comment">Kommentarer</a></dd>
        <% else %>
          <dd class="active"><a href="#comment">Kommentarer</a></dd>
        <% end %>
        </dl>
        <ul class="tabs-content">
        <% if @map.status_updates.any? %>
          <li class="active" id="statusTab">
            <%= render 'status_updates/shared/status_updates', :updates => @map.status_updates %>
          </li>
          <li id="commentTab">
            <%= render 'map_comments/shared/map_comments', :map => @map %>
          </li>
        <% else %>
          <li id="commentTab" class="active">
            <%= render 'map_comments/shared/map_comments', :map => @map %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>

  </section> <!-- role[main] -->

  <!-- Sidebar -->
  <section id="sidebar" role="complementary">

    <div class="row created-by">
      <div class="twelve columns">
        <div class="panel radius">
          <% if @map.user.provider? %>
          <img src="<%= @map.user.profile_image %>" alt="" class="profile-image-medium" />
          <% else %>
            <%= gravatar_image_tag(@map.user.email,
                        alt: @map.user.email,
                        class: "",
                        gravatar: { default: 'https://assets.github.com/images/gravatars/gravatar-140.png', size: 35 }) %>
          <% end %>

          <div class="profile-name">av <%= link_to @map.user.name || @map.user.username, profile_path(@map.user.slug) %></div>
          <span class="created-time"><%= time_ago( @map.created_at ) %></span>

          <% if @map.user == current_user %>
          <ul class="map-settings">
            <li>
                <%= link_to "Redigera karta", edit_profile_map_path(@map.user.slug, @map.slug), :title => 'Redigera kartan' %>
            </li> |
            <li><%= link_to "Ta bort karta", profile_map_path(@map.user.slug, @map.slug),
                    method: :delete, confirm: "Vill du ta bort kartan?", :title => 'Ta bort kartan' %>
            </li>
          </ul>
          <% end %>
          <div class="row">
            <div class="twelve columns">
              <ul class="no-bullet" id="counter-map">
                <li><i class="foundicon-page"></i> <%= @map.map_views %> sidvisningar</li>
                <li><i class="foundicon-location"></i> <%= @map.marks.count %> markeringar</li>
                <li><i class="foundicon-people"></i> <%= render 'maps/shared/follow_count' %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <% unless @map.user == current_user %>
    <div class="row show-for-small">
        <div class="eight columns centered">
          <div class="map-meta">
            <%= render 'maps/shared/follow_button' %>
          </div>
        </div>
    </div>
    <% end %>
    
    <div class="row">
      <div class="twelve columns">
        <h5 class="subheader">Markeringar</h5>
        <% if @map.user == current_user %>
            <p class="marks"><i class="foundicon-plus"></i> <%= link_to "Lägg till markering", new_profile_map_mark_path(@map.user.slug, @map.slug) %></p>
        <% end %>
        <ul class="no-bullet">
          <%= render 'maps/shared/list_marks' %>
        </ul>
      </div>
    </div>

  </section> <!-- role[complementary] -->
</div>

app/views/maps/show_private.html.erb
<h3><%= @map.name %> är privat</h3>