config/routes.rb
Wp102dv401::Application.routes.draw do

  mount RailsAdmin::Engine => '/kartr-admin', :as => 'rails_admin'

  get "instagram/index"

  get "instagram/new"

  get "javascripts/maps"

  get "/om-kartr" => "pages#about", as: :pages_about
  get "/anvandarvillkor" => "pages#terms", as: :pages_terms
  get "/sekretess" => "pages#privacy", as: :pages_privacy
  get "/hjalp" => "pages#help", as: :pages_help

  get "/api" => "pages#api", as: :pages_api

  match "javascripts/maps.:format" => "javascripts#maps"
  match "/api/v1/:api_key.:format" => "maps#embed", as: :embed

  devise_for :users, controllers: {
    omniauth_callbacks: "authentications",
    registrations: "registrations"
  }

  devise_scope :user do
    delete "/logga-ut" => "devise/sessions#destroy", as: :destroy_user_session
    get "/ny-bekraftelse" => "devise/confirmations#new", as: :new_user_confirmation
    get "/nytt-losenord" => "devise/passwords#new", as: :new_user_password
    get "/registrering" => "registrations#new", as: :new_user_registration
    get "/redigera-profil" => "registrations#edit", as: :edit_user_registration

    get "/users/auth/:provider" => "authentications#passthru"
  end
  get "/search" => "maps#search", as: :maps_search

  get "/searches/search"
  get "/kartor/resultat/:query" => "searches#result", as: :search_result
  get "/searches/autocomplete"

  scope(path_names: { new: "ny", edit: "redigera" }) do

    resources :home, only: [ :index ], path: "hem"

    resources :dashboard, only: [ :index ], path: "startsida"

    resources :profiles, only: [], path: '' do
      get "show_maps", path: "kartlista"

      resources :maps, except: [ :index ], path: "kartor" do

        resources :marks, only: [ :new, :edit, :create ], path: "markeringar"
      end
    end

    resources :profiles, only: [ :index ], path: "profiler"
    resources :profiles, only: [ :show ], path: "profil"

    resources :maps, only: [ :index ], path: "kartor" do
      post "toggle"

      resources :marks, path: "markeringar"

      resources :status_updates, only: [ :create ], path: "skapa-uppdatering"
      resources :map_comments, only: [ :create ], path: "skapa-kommentar"
    end

    resources :map_comments, only: [ :update, :destroy ], path: "kart-kommentarer" do
      post "toggle_like"
    end

    resources :status_updates, only: [ :update, :destroy ], path: "status-uppdateringar" do
      post "toggle_like"

      resources :status_comments, only: [ :create ], path: "kommentarer"
    end

    resources :status_comments, only: [ :update, :destroy ], path: "status-kommentarer" do
      post "toggle_like"
    end

    resources :marks, only: [ :update, :destroy ], path: "markeringar"

  end

  root to: "home#index"

end

app/models/map_comment.rb
class MapComment < ActiveRecord::Base
  belongs_to :map
  belongs_to :user

  acts_as_likeable

  # attributes
  attr_accessible :content

  # validation
  validates :content, presence: true, length: { maximum: 5120 }

end

app/controllers/map_comments_controller.rb
class MapCommentsController < ApplicationController
  before_filter :authenticate_user!

  # POST map/:id/map_comments/toggle_like
  def toggle_like
    @map_comment = MapComment.find(params[:map_comment_id])

    if current_user.likes?(@map_comment)
      current_user.unlike!(@map_comment)
    else
      current_user.like!(@map_comment)
    end
    render template: 'map_comments/remote/like_button_toggle'
  end

  # POST map/:id/map_comments
  def create
    @map = Map.find(params[:map_id])
    #Skapar ny kartkommentar från post-parametrarna samt lägger till aktuella användaren
    @comment = MapComment.new(params[:map_comment]) do |c|
      c.user = current_user
      c.map = @map
    end

    if @comment.save
      flash[:success] = t :created, scope: [:map_comments]
    else
      flash[:error] = t :failed_to_create, scope: [:map_comments]
    end
    render template: 'map_comments/remote/render_new_map_comment'
  end

  # DELETE /maps/:id/map_comments/1
  # DELETE /maps/:id/map_comments/1.json
  def destroy

    @comment = MapComment.find(params[:id])
    @destroyed_comment = @comment
    @map = @comment.map

    if current_user == @comment.user || current_user == @map.user
      if @comment.destroy
        flash[:success] = t :removed, scope: [:map_comments]
      else
        flash[:error] = t :failed_to_remove, scope: [:map_comments]
      end
    else
      flash[:error] = t :access_denied
    end
    render template: 'map_comments/remote/remove_map_comment'
  end
end

app/helpers/map_comments_helper.rb
module MapCommentsHelper
end

app/views/map_comments/shared/_form.html.erb
<%= form_for(@map_comment, url: map_map_comments_path(@map.id, @map_comment), remote: true) do |f| %>
    <div class="content">
      <%= f.text_field :content, placeholder: "Skriv en kommentar..." %>
    </div>
<% end %>

app/views/map_comments/shared/_like_button.html.erb
<ul>
<% if current_user.likes?(comment) %>
  <li>
    <%= link_to 'Sluta gilla ', map_comment_toggle_like_path(comment), method: :post, remote: true %>
  </li>|
<% else %>
  <li>
    <%= link_to 'Gilla ', map_comment_toggle_like_path(comment), method: :post, remote: true %>
    </li>|
<% end %>
<% if current_user == comment.user %>
  <li>
    <%= link_to 'Ta bort ', map_comment_path(comment), confirm: 'Vill du ta bort Kommentaren?', method: :delete, remote: true %>
  </li>|
<% end %>
  <li class="created-at"><%= time_ago(comment.created_at) %></li>
</ul>
<div class="status-comment-statistics">
  <span class="status-update-likes"><%= like_count_string(comment) %></span>
</div>

app/views/map_comments/shared/_map_comment.html.erb
<li id="map-comment-<%= comment.id %>" class="map-comment">
  <span class="map-comment-image">
    <% if comment.user.provider? %>
      <img src="<%= comment.user.profile_image %>" alt="" class="profile-image-medium" />
    <% else %>
      <%= gravatar_image_tag( comment.user.email, 
                    alt: comment.user.email,
                    class: 'profile-image-small',
                    gravatar: { default: 'https://assets.github.com/images/gravatars/gravatar-140.png' } ) %>
    <% end %>
  </span>
  <p class="map-comment-body">
    <span class="author">
      <%= link_to comment.user.name || comment.user.username, profile_path( comment.user.slug ) %>
    </span>
    <%= format_text(comment.content) %>
  </p>
  <div class="map-comment-footer">
    <div id="map-comment-like-button-<%= comment.id %>">
      <%= render 'map_comments/shared/like_button', comment: comment %>
    </div>
  </div>
</li>

app/views/map_comments/shared/_map_comments.erb
<div class="map-comment-list">
  <ul class="map-comments">
    <% comments.each do |c| %>
        <li>
          <p><span><%= c.user.username %>: </span><%= c.content %></p>
          <div class="map-comment-footer">
            <span class="created-at"><%= time_ago(c.created_at) %></span>
            <% if current_user == c.user %>
                <%= link_to 'Ta bort', map_map_comment_path(@map.id, c.id), :confirm => 'Vill du ta bort kommentaren?', :method => :delete %>
            <% end %>
          </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/map_comments/shared/_map_comments.html.erb
<section class="map-comment-wrapper">
  <ul id="map-<%= map.id %>-comment-list" class="map-comments">
    <li class="map-comment-form">
      <%= render "map_comments/shared/form" %>
    </li>
    <% if map.map_comments.any? %>
        <% map.map_comments.each do |c| %>
            <%= render 'map_comments/shared/map_comment', comment: c %>
        <% end %>
    <% end %>
  </ul>
</section>